use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Challenge nonce generated by the host application (e.g. Foundry VTT or local engine)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ChallengeNonce {
    pub nonce: String,
    pub package_id: String,
    pub timestamp: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

impl ChallengeNonce {
    pub fn new(package_id: String, nonce: String, ttl_seconds: i64) -> Self {
        let now = Utc::now();
        Self {
            nonce,
            package_id,
            timestamp: now,
            expires_at: now + chrono::Duration::seconds(ttl_seconds),
        }
    }

    pub fn is_expired(&self) -> bool {
        Utc::now() > self.expires_at
    }
}

/// Zero-knowledge proof verifying ownership without revealing user key or correlatable identity
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ZkProof {
    pub proof_bytes: Vec<u8>,
    pub public_inputs: ProofInputs,
}

/// Public inputs exposed to verifier
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProofInputs {
    pub challenge_nonce: String,
    pub package_id: String,
    pub content_digest: String,
    pub publisher_pubkey_hash: String,
}

/// Publisher verification key
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationKey {
    pub publisher_id: String,
    pub key_bytes: Vec<u8>,
}

/// Trait defining ZK Prover interface (to be implemented with arkworks-rs / groth16)
pub trait ZkProver {
    fn prove(
        &self,
        secret_key: &[u8],
        credential: &crate::credential::KryptotomeCredential,
        challenge: &ChallengeNonce,
    ) -> crate::error::Result<ZkProof>;
}

/// Trait defining ZK Verifier interface
pub trait ZkVerifier {
    fn verify(
        &self,
        vk: &VerificationKey,
        challenge: &ChallengeNonce,
        proof: &ZkProof,
    ) -> crate::error::Result<bool>;
}
