use base64::prelude::*;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Challenge nonce generated by the host application (e.g. Foundry VTT or local engine)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ChallengeNonce {
    pub nonce: String,
    pub package_id: String,
    pub timestamp: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

impl ChallengeNonce {
    pub fn new(package_id: String, nonce: String, ttl_seconds: i64) -> Self {
        let now = Utc::now();
        Self {
            nonce,
            package_id,
            timestamp: now,
            expires_at: now + chrono::Duration::seconds(ttl_seconds),
        }
    }

    pub fn is_expired(&self) -> bool {
        Utc::now() > self.expires_at
    }
}

/// Zero-knowledge proof verifying ownership without revealing user key or correlatable identity
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ZkProof {
    pub proof_bytes: Vec<u8>,
    pub public_inputs: ProofInputs,
}

impl ZkProof {
    /// Encodes proof bytes as standard Base64
    pub fn to_base64(&self) -> String {
        base64::prelude::BASE64_STANDARD.encode(&self.proof_bytes)
    }

    /// Encodes proof bytes as URL-safe unpadded Base64
    pub fn to_base64_url(&self) -> String {
        base64::prelude::BASE64_URL_SAFE_NO_PAD.encode(&self.proof_bytes)
    }

    /// Decodes proof from Base64 string with public inputs
    pub fn from_base64(s: &str, public_inputs: ProofInputs) -> crate::error::Result<Self> {
        let proof_bytes = base64::prelude::BASE64_STANDARD
            .decode(s.trim())
            .or_else(|_| base64::prelude::BASE64_URL_SAFE_NO_PAD.decode(s.trim()))
            .map_err(|e| crate::error::KryptotomeError::Detailed {
                code: crate::error::KryptotomeErrorCode::Kryp303MalformedProofEncoding,
                message: format!("Invalid proof Base64: {}", e),
            })?;
        Ok(Self {
            proof_bytes,
            public_inputs,
        })
    }
}

/// Public inputs exposed to verifier
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProofInputs {
    pub challenge_nonce: String,
    pub package_id: String,
    pub content_digest: String,
    pub publisher_pubkey_hash: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub holder_commitment: Option<String>,
}

/// Publisher verification key
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationKey {
    pub publisher_id: String,
    pub key_bytes: Vec<u8>,
}

/// Trait defining ZK Prover interface (to be implemented with arkworks-rs / groth16)
pub trait ZkProver {
    fn prove(
        &self,
        secret_key: &[u8],
        credential: &crate::credential::KryptotomeCredential,
        challenge: &ChallengeNonce,
    ) -> crate::error::Result<ZkProof>;
}

/// Trait defining ZK Verifier interface
pub trait ZkVerifier {
    fn verify(
        &self,
        vk: &VerificationKey,
        challenge: &ChallengeNonce,
        proof: &ZkProof,
    ) -> crate::error::Result<bool>;
}
